name: Build and Release

on:
   push:
      branches:
         - main # Auto run when push to main branch
      tags:
         - 'v*' # Trigger when tag starts with 'v' (e.g., v1.0.0)
   pull_request:
      branches:
         - main # Run on PR to main branch
   workflow_dispatch: # Allow manual trigger

jobs:
   build:
      runs-on: windows-latest # Use Windows to build exe

      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Set up Python
           uses: actions/setup-python@v4
           with:
              python-version: '3.12'

         - name: Install uv
           uses: astral-sh/setup-uv@v4
           with:
              enable-cache: true

         - name: Install dependencies
           run: |
              uv sync
              uv add pyinstaller

         - name: Build executable
           run: |
              uv run pyinstaller build.spec

         - name: Upload artifact
           uses: actions/upload-artifact@v4
           with:
              name: FC_Online_Tool-${{ github.sha }}
              path: dist/FC_Online_Tool.exe

   release:
      needs: build
      runs-on: ubuntu-latest
      if: startsWith(github.ref, 'refs/tags/') # Only create release when there's a tag

      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Download artifact
           uses: actions/download-artifact@v4
           with:
              name: FC_Online_Tool-${{ github.sha }}
              path: ./dist/

         - name: Create Release
           uses: softprops/action-gh-release@v2
           with:
              files: ./dist/FC_Online_Tool.exe
              generate_release_notes: true
              draft: false
              prerelease: false
              name: 'FC Online Tool ${{ github.ref_name }}'
              body: |
                 ## 🚀 FC Online Automation Tool ${{ github.ref_name }}

                 ### 📦 Download
                 - **FC_Online_Tool.exe** - Ready to run Windows executable

                 ### 🔧 Installation
                 1. Download the exe file
                 2. Run as administrator (recommended)
                 3. Windows Defender might show a warning - click "More info" then "Run anyway"

                 ### ✨ Features
                 - GUI interface for easy configuration
                 - Automated FC Online operations
                 - Real-time status monitoring
                 - Dark/Light theme support

                 ---
                 **Note**: This is an automated release built from source code.
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
